-- Create the contents table
create table public.contents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'artigos', 'reflexoes', 'noticias'
  title text not null,
  category text,
  "categoryName" text, -- Quoted because of mixed case if preferred
  excerpt text,
  image text,
  author text,
  content text,
  date text,
  "readTime" text,
  tags text[]
);

-- Set up Row Level Security (RLS)
-- For development, we can allow public read/write.
alter table public.contents enable row level security;

create policy "Enable read access for all users"
on public.contents for select
using (true);

create policy "Enable insert for all users"
on public.contents for insert
with check (true);

create policy "Enable update for all users"
on public.contents for update
using (true);

create policy "Enable delete for all users"
on public.contents for delete
using (true);

-- Insert initial data (from content.ts)
-- Artigos
insert into public.contents (type, title, category, "categoryName", excerpt, image, author, content, date, "readTime", tags)
values 
(
  'artigos',
  'Curatela: Instrumento de Proteção e Cuidado no Ordenamento Jurídico Brasileiro',
  'civil',
  'Direito Civil',
  'Análise do instrumento da curatela como forma de proteção da pessoa com incapacidade.',
  'https://res.cloudinary.com/dqewxdbfx/image/upload/v1762624801/maos-dadas-umas-as-outras-para-apoio_page-0001_n0v2bn.jpg',
  'Redação',
  '<ul><li><strong>Breve Introdução</strong></li></ul><p><span style="font-weight: 400;">A Curatela no ordenamento jurídico brasileiro está prevista</span> <span style="font-weight: 400;">no</span><strong> Código Civil, Lei </strong><strong>nº</strong><strong> 10.406 de 10 de janeiro de 2002</strong>...</p>',
  '01 de Fevereiro de 2025',
  '10 min de leitura',
  ARRAY['Curatela', 'Direito Civil', 'Proteção', 'Incapacidade']
),
(
  'artigos',
  'Tutela: Proteção Integral de Menores no Ordenamento Jurídico Brasileiro',
  'civil',
  'Direito Civil',
  'Análise do instrumento da tutela como forma de proteção do menor.',
  'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
  'Redação',
  '<p><strong>Breve Introdução</strong></p><p>A Tutela de menores no ordenamento jurídico brasileiro está prevista no Código Civil...</p>',
  '01 de março de 2025',
  '30 min de leitura',
  ARRAY['Tutela', 'Direito Civil', 'Menores', 'Proteção']
),
(
  'artigos',
  'Princípios Fundamentais da Constituição Federal',
  'constitucional',
  'Direito Constitucional',
  'Análise dos princípios fundamentais que regem o ordenamento jurídico brasileiro.',
  'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
  'Redação',
  '<p><strong>Princípios Fundamentais</strong></p><p>A Constituição Federal de 1988 estabelece os princípios fundamentais...</p>',
  '15 de março de 2025',
  '15 min de leitura',
  ARRAY['Constituição', 'Princípios', 'Direitos Fundamentais']
);

-- Reflexoes
insert into public.contents (type, title, category, "categoryName", excerpt, image, author, content, date, "readTime", tags)
values 
(
  'reflexoes',
  'INTELIGÊNCIA',
  'reflexoes',
  'Reflexão',
  'Reflexão sobre a inteligência como capacidade de aprender com os erros e recomeçar com mais sabedoria',
  'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800',
  'Redação',
  '<p><strong>INTELIGÊNCIA</strong></p><p>&nbsp;</p>...',
  '05 de setembro de 2025',
  '5 min de leitura',
  ARRAY['Objetivo', 'Estratégia', 'Habilidade', 'Compreensão', 'Recomeçar']
);
